#!/usr/bin/env node
// TEST-ONLY stand-in for the real `pg_dump` binary — used exclusively by
// deploy/backup.test.ts (tasks.md 8.3). See that file's module doc for WHY
// this exists: this sandbox's local "Postgres" (`npx prisma dev`) is
// actually PGlite (an in-process WASM Postgres), which ships no real
// `pg_dump`/`psql` executables, and this Windows dev box has no system
// PostgreSQL install either. deploy/backup.sh itself is unmodified for this
// — it just calls the literal command name `pg_dump`, exactly as it will
// against the REAL `pg_dump` installed on the DonWeb VPS
// (deploy/DEPLOY.md's `apt install postgresql-client` step). The test
// prepends this script's directory (wrapped as an executable named
// `pg_dump`) onto PATH so backup.sh's `pg_dump` invocation resolves here
// instead, for local verification purposes only.
//
// This performs a REAL, generic schema+data dump via the same `pg` driver
// (node-postgres) the app itself depends on — introspecting
// information_schema/pg_catalog and emitting plain SQL (CREATE TYPE for
// enums, CREATE TABLE with PK/UNIQUE — but deliberately NOT foreign keys —
// then INSERT per row, then ALTER TABLE ... ADD CONSTRAINT for foreign
// keys at the very end). Deferring FK constraints to the end mirrors real
// pg_dump's own strategy and means insert order never has to respect FK
// dependency order. CHECK constraints (e.g. Variant.onHand >= 0) are
// intentionally NOT re-emitted — restorability here is judged by row
// counts (see the test), not full DDL fidelity, and re-deriving arbitrary
// CHECK expression SQL generically from pg_catalog is out of scope for a
// test double. This is NOT a general-purpose pg_dump replacement; it only
// needs to correctly round-trip Dominique's actual column types (text,
// integer, boolean, timestamp/date/time, numeric, json, enum).
"use strict";

const fs = require("node:fs");
const { Client } = require("pg");

function parseArgs(argv) {
  let connectionString;
  let outFile;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "-f" || arg === "--file") {
      outFile = argv[i + 1];
      i += 1;
    } else if (!arg.startsWith("-")) {
      connectionString = arg;
    }
    // Everything else (--no-owner, --no-privileges, --format=plain, ...)
    // is accepted and ignored — this dumper only ever emits plain SQL.
  }
  if (!connectionString) {
    throw new Error("fake-pg-dump: missing connection string argument");
  }
  if (!outFile) {
    throw new Error("fake-pg-dump: missing -f <file> argument");
  }
  return { connectionString, outFile };
}

function quoteIdent(name) {
  return `"${name.replace(/"/g, '""')}"`;
}

function sqlType(column) {
  const { data_type: dataType, udt_name: udtName, character_maximum_length: maxLen, numeric_precision: precision, numeric_scale: scale } = column;
  switch (dataType) {
    case "character varying":
      return maxLen ? `varchar(${maxLen})` : "varchar";
    case "text":
      return "text";
    case "integer":
      return "integer";
    case "boolean":
      return "boolean";
    case "timestamp without time zone":
      return "timestamp";
    case "timestamp with time zone":
      return "timestamptz";
    case "date":
      return "date";
    case "time without time zone":
      return "time";
    case "numeric":
      return precision != null ? `numeric(${precision},${scale ?? 0})` : "numeric";
    case "json":
      return "json";
    case "jsonb":
      return "jsonb";
    case "USER-DEFINED":
      return quoteIdent(udtName);
    default:
      return dataType;
  }
}

function serializeValue(value, column) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number") return String(value);
  if (value instanceof Date) {
    // node-postgres returns JS Date objects for timestamp/timestamptz/date
    // columns. ISO-8601 text is parseable by Postgres for all of those.
    return `'${value.toISOString()}'`;
  }
  if (column.data_type === "json" || column.data_type === "jsonb") {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  }
  // Strings (including enum labels, `time` columns which node-postgres
  // returns as plain "HH:MM:SS" strings, and numeric columns — node-postgres
  // returns NUMERIC as a string to avoid float precision loss, and a bare
  // numeric-looking string is a valid SQL numeric literal without quotes
  // too, but quoting it is also valid Postgres input syntax and simpler).
  return `'${String(value).replace(/'/g, "''")}'`;
}

async function main() {
  const { connectionString, outFile } = parseArgs(process.argv.slice(2));
  const client = new Client({ connectionString });
  await client.connect();

  const lines = [
    "-- Generated by deploy/testing/fake-pg-dump.cjs (test double, see its module doc)",
    "BEGIN;",
    "",
  ];

  try {
    const { rows: tables } = await client.query(
      `SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
       ORDER BY table_name`,
    );

    const { rows: enumRows } = await client.query(
      `SELECT t.typname, e.enumlabel
       FROM pg_type t
       JOIN pg_enum e ON t.oid = e.enumtypid
       JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
       WHERE n.nspname = 'public'
       ORDER BY t.typname, e.enumsortorder`,
    );
    const enumsByName = new Map();
    for (const row of enumRows) {
      if (!enumsByName.has(row.typname)) enumsByName.set(row.typname, []);
      enumsByName.get(row.typname).push(row.enumlabel);
    }
    for (const [typname, labels] of enumsByName) {
      const labelList = labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(", ");
      lines.push(`CREATE TYPE ${quoteIdent(typname)} AS ENUM (${labelList});`);
    }
    lines.push("");

    const columnsByTable = new Map();
    for (const { table_name: tableName } of tables) {
      const { rows: columns } = await client.query(
        `SELECT column_name, data_type, udt_name, is_nullable,
                character_maximum_length, numeric_precision, numeric_scale
         FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = $1
         ORDER BY ordinal_position`,
        [tableName],
      );
      columnsByTable.set(tableName, columns);

      const { rows: pkRows } = await client.query(
        `SELECT kcu.column_name
         FROM information_schema.table_constraints tc
         JOIN information_schema.key_column_usage kcu
           ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
         WHERE tc.constraint_type = 'PRIMARY KEY' AND tc.table_schema = 'public' AND tc.table_name = $1
         ORDER BY kcu.ordinal_position`,
        [tableName],
      );

      const colDefs = columns.map((col) => {
        const notNull = col.is_nullable === "NO" ? " NOT NULL" : "";
        return `  ${quoteIdent(col.column_name)} ${sqlType(col)}${notNull}`;
      });
      if (pkRows.length > 0) {
        colDefs.push(`  PRIMARY KEY (${pkRows.map((r) => quoteIdent(r.column_name)).join(", ")})`);
      }
      lines.push(`CREATE TABLE ${quoteIdent(tableName)} (\n${colDefs.join(",\n")}\n);`);
    }
    lines.push("");

    // Non-PK UNIQUE constraints (needed so later ALTER TABLE ... FOREIGN KEY
    // statements referencing them can validate).
    const { rows: uniqueRows } = await client.query(
      `SELECT tc.table_name, tc.constraint_name, kcu.column_name, kcu.ordinal_position
       FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
       WHERE tc.constraint_type = 'UNIQUE' AND tc.table_schema = 'public'
       ORDER BY tc.table_name, tc.constraint_name, kcu.ordinal_position`,
    );
    const uniqueByConstraint = new Map();
    for (const row of uniqueRows) {
      if (!uniqueByConstraint.has(row.constraint_name)) {
        uniqueByConstraint.set(row.constraint_name, { table: row.table_name, columns: [] });
      }
      uniqueByConstraint.get(row.constraint_name).columns.push(row.column_name);
    }
    for (const [name, { table, columns }] of uniqueByConstraint) {
      lines.push(
        `ALTER TABLE ${quoteIdent(table)} ADD CONSTRAINT ${quoteIdent(name)} UNIQUE (${columns
          .map(quoteIdent)
          .join(", ")});`,
      );
    }
    lines.push("");

    // Data — INSERT per row. Emitted BEFORE foreign keys are added below,
    // so insert order never needs to respect FK dependency order (same
    // strategy real pg_dump uses in plain-format dumps).
    for (const { table_name: tableName } of tables) {
      const columns = columnsByTable.get(tableName);
      const { rows } = await client.query(`SELECT * FROM ${quoteIdent(tableName)}`);
      for (const row of rows) {
        const columnNames = columns.map((c) => c.column_name);
        const values = columns.map((col) => serializeValue(row[col.column_name], col));
        lines.push(
          `INSERT INTO ${quoteIdent(tableName)} (${columnNames.map(quoteIdent).join(", ")}) VALUES (${values.join(", ")});`,
        );
      }
    }
    lines.push("");

    // Foreign keys — added last (deferred strategy, see module doc above).
    const { rows: fkRows } = await client.query(
      `SELECT
         tc.constraint_name, tc.table_name AS src_table, kcu.column_name AS src_column,
         ccu.table_name AS ref_table, ccu.column_name AS ref_column
       FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
       JOIN information_schema.constraint_column_usage ccu
         ON tc.constraint_name = ccu.constraint_name AND tc.table_schema = ccu.table_schema
       WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'
       ORDER BY tc.constraint_name`,
    );
    for (const fk of fkRows) {
      lines.push(
        `ALTER TABLE ${quoteIdent(fk.src_table)} ADD CONSTRAINT ${quoteIdent(fk.constraint_name)} ` +
          `FOREIGN KEY (${quoteIdent(fk.src_column)}) REFERENCES ${quoteIdent(fk.ref_table)} (${quoteIdent(fk.ref_column)});`,
      );
    }

    lines.push("", "COMMIT;", "");
  } finally {
    await client.end();
  }

  fs.writeFileSync(outFile, lines.join("\n"), "utf8");
}

main().catch((error) => {
  console.error("fake-pg-dump failed:", error);
  process.exitCode = 1;
});
